# Generated by Django 4.2.3 on 2023-09-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
        migrations.AddField(
            model_name='reserva',
            name='finalizado',
            field=models.BooleanField(blank=True, default=False, verbose_name='Finalizado'),
        ),
    ]
